### ISSUE TITLE
Add periodic tests

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#103]
Run the tests e.g. daily or weekly as a way to learn when the world changes in a way that breaks celltests. 

Might consider having such cron test results be ignored/silent by default. That way, can ignore churn in test passes/failures because of dependencies changing, but if the tests keep failing, there's an easy to look at record of when the problem started (helps a lot to narrow problems down).

**Comment by timkpaine** [comment]
This is easy to configure in azure

**Comment by timkpaine** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops

**Comment by timkpaine** [comment]
I've added nightly runs

![Screen Shot 2020-05-11 at 12 49 00 PM](https://user-images.githubusercontent.com/3105306/81587980-d283ae00-9385-11ea-901c-3c368c4f4f0e.png)

**Comment by ceball** [comment]
I can't actually find the nightly runs after clicking around for a few mins...any chance you could somehow link to where they are? 😂

![sched](https://user-images.githubusercontent.com/1929/82954865-8059a400-9fa5-11ea-8685-7e7ca5454705.PNG)

Reading https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml, it looks possible to add via yaml, which would probably be easier for me.

**Comment by timkpaine** [comment]
https://github.com/jpmorganchase/nbcelltests/pull/198
