### ISSUE TITLE
Replace --forked in internal tests

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#107]
[Update: replaced link to comment with full description.]

## Problem

The test suite is run twice on azure: once "normally", and once using `--forked`. But:

1. We no longer need to run a "forked" version of the tests, i.e. we no longer need a 
 version of the test suite that guarantees one test per process (i.e. one cell execution per kernel).

2. `--forked` does not work on windows.

## Proposed solution

* Remove any special handling in the test suite (i.e. within `nbcelltests/tests/`) for the "forked" case.

* Fix `'pytest-xdist ; sys_platform != "win32"'` in setup.py to always install pytest-xdist no matter the platform (I believe it works on windows, just some options e.g. `--forked` don't work/have meaning on windows).

* Replace the `pytest --forked` invocation of the test suite with probably `pytest -n`. That likely means editing `Makefile` and `.azure/pipelines.yml` and `.azure/dev-template.yml`.

Working on the test suite of a testing tool unfortunately likely requires some knowledge of python's test tools (unittest, pytest). Please feel free to ask if you see something that looks weird - it might be just bad code, or it might be necessary for some awkward reason, and it's not always easy to tell.

## Background

`--forked` was originally added to the test suite so that we could run two versions of the test suite:
1. the original way, with multiple tests in the same process (i.e. multiple tests sharing a kernel)
2. with one test per process (i.e. one kernel per test), to identify and fix issues with kernel state (e.g. multiple executions of the same cell in a given kernel).

The full test suite originally only passed in the second case. You can see an example of a test that failed in the first case in test_test.py; the test below originally passed _only_ in the forked case, because only in the forked case were cells not repeatedly executed in the same kernel:

```python
class TestCumulativeRun(_TestCellTests):
    [...]
    def test_state(self):
        """In the expected case, the five cells of the notebook should work
        out as follows:

             cell    test   state
        1:    -       -       -
        2:   x=0      -      x=0
        3:   x+=1     -      x=1
        4:   x+=1     -      x=2
        5:    -      x+=1    x=3

        However, these tests originally detected repeated execution of
        cells in the same kernel. Cell 2 actually only sets x to 0 if
        x is not already defined; if x is already defined, cell 2 does
        not change x's value. If for some reason each test results in
        multiple executions of the cells, the results will look like
        this:

             cell    test   state
        1:    -       -       -
        2:    -       -      x>0   (bad; x was previously defined in kernel)
        3:   x+=1     -      x>1   (bad)
        4:   x+=1     -      x>2   (bad)
        5:    -      x+=1    x>3   (bad)
        """
```

So, the `--forked` version of the test suite was not there to catch a bug - the bug was caught by the regular test suite - but to demonstrate the reason for the regular test suite failing. The bug is long since fixed, so it's fine to remove the `--forked` version and handling for it.

However, it's still useful to run a distributed as well as non-distributed version of the test suite in order to increase the chance of catching certain bugs, hence the suggestion to replace the `--forked` invocation with `-n` (with just some reasonable `n`, e.g. 2 or whatever).

See https://github.com/jpmorganchase/nbcelltests/pull/90#discussion_r423704977 for original discussion.

**Comment by utsavm9** [comment]
In https://github.com/jpmorganchase/nbcelltests/pull/90#discussion_r423744262, you say that `--forked` can be removed. Do you just want to remove code related to `--forked` test, or is it needed to be replaced by some other option?

Also, I am not sure what `-n2` is.

**Comment by ceball** [comment]
@utsavm9 Thanks for your helpful clarifying questions. I have written a full description in the issue now. I hope my description answers your first question, but please feel free to ask for further clarifications.

> Also, I am not sure what -n2 is?

I'm on linux, so the below might vary a bit for you if you're not, but after installing `pytest-xdist` I see this:

```
$ pytest -v
=============================== test session starts ================================
platform linux -- Python 3.7.9, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- [...]
cachedir: .pytest_cache
rootdir: [...]
plugins: forked-1.3.0, xdist-2.1.0
collected 0 items                                                                  

============================== no tests ran in 0.01s ===============================
```

```
$ pytest --help
[...]
forked subprocess test execution:
  --forked              box each test run in a separate process (unix)

distributed and subprocess testing:
  -n numprocesses, --numprocesses=numprocesses
                        shortcut for '--dist=load --tx=NUM*popen', you can use
                        'auto' here for auto detection CPUs number on host system
                        and it will be 0 when used with --pdb
  --maxprocesses=maxprocesses
                        limit the maximum number of workers to process the tests
                        when using --numprocesses=auto
  [...]
```

And `-n` should work fine on windows, unlike `--forked`.
