### ISSUE TITLE
Speculatively install lab extension alongside nbcelltests?

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#135]
I believe installation is just copying to "share". Then when lab is next started, it will request to do a re-build. 

If lab is not installed, it just uses up some disk space. 

Would avoid separate lab extension installation step.

**Comment by ceball** [comment]
From setup.py, looks like this is actually done already. Just need to check it works.

**Comment by timkpaine** [comment]
might need to update the paths for the js folder
