### ISSUE TITLE
Allow notebook authors to disable lint checks other than by comments in code?

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#141]
This could be done by any or all of cell tags, cell metadata, notebook metadata.

And when running `nbcelltests.lint`, you should be able to define how notebook authors can disable checks (if at all).

**Comment by ceball** [comment]
Disabling via comment was added in 0.2:
> I'm not sure I like disabling rules such as number of cells per notebook via a comment in a code cell, but this might allow someone to integrate with a pre-existing system that already uses such comments for python code.

**Comment by timkpaine** [comment]
duplicate, moving to https://github.com/jpmorganchase/nbcelltests/issues/171
