### ISSUE TITLE
License and readme being missed from npm package

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#159]
Right after publishing 0.2.0, I noticed that the readme and license are missing from jupyterlab_celltests. I'd previously created and published 0.2.0a2 to catch this kind of thing, but somehow I didn't notice. I assume this is related to the earlier repo reorg (creation of js folder).

What's the right solution? 
  * Use a symlink? (Is support for that on windows now widespread enough/doesn't matter if it's missing on windows as we'll never build packages there?)
  * Separate readme and license files for jupyterlab_celltests? (If there's enough different to say about them - seems unlikely?) 
  * Copy the existing license and readme in at package time? (If so, how does one usually do that?)

**Comment by ceball** [comment]
(There being apparently no way to specify the location: https://docs.npmjs.com/about-package-readme-files)

**Comment by timkpaine** [comment]
it should be easy to copy prior to dist:
```
"prepublishOnly": "cpx "../README.md" "./README.md" && cpx "../LICENSE" "./LICENSE" && npm run build",
```

**Comment by ceball** [comment]
Ok, thanks, you're going for option 3 above (I should have numbered them!), using a cross-platform file copy util installed via npm (i.e. add to dev dependencies in package.json).

That seems fine to me - will do it.

(Though it's some painful-looking command string 😂. I guess all the quotes aren't necessary - we know the path names, and they're straightforward. Tell me if I'm wrong!)
