### ISSUE TITLE
namespace our metadata

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#170]
@vidartf do you happen to know an example/standard to follow?

**Comment by timkpaine** [comment]
technically it is namespaced in `"tests"` for cells and `"celltests"` for notebook. Not sure there is any formal way of "formalizing" this though.

**Comment by vidartf** [comment]
IIRC I think the concern was about the somewhat high chance of a collision on the `tests` key. In general, I think the "core" Jupyter format tries to avoid speccing the metadata, instead saying that anything formal should be formalized *outside* of metadata (via a JEP). Instead the recommendation is to namespace metadata in a way that avoids accidental collisions (namespacing on PyPI package name is an good alternative there). If we are claiming the cell-metadata `test` key for ourselves, we should at least try to make a spec that others can use, and do a review to see if there are already other projects that use this key.

**Comment by timkpaine** [comment]
shall we use `celltests` or `nbcelltests` for both notebook and cell metadata?
