### ISSUE TITLE
Have I written a test or not?

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#183]
When you click through cells while looking at the "CELLTESTS" box, you can't tell if you've actually written a test without expanding 'advanced tools' and looking at the 'cell metadata'. It's pretty confusing.

**Comment by timkpaine** [comment]
how do you feel about this minimal indicator?
![tmp](https://user-images.githubusercontent.com/3105306/90827080-91e2eb80-e309-11ea-9e19-b52608b4ac35.gif)

**Comment by ceball** [comment]
It's great to have an indicator! And I can see what you've implemented will work for me. It's a definite improvement, so we should add this change (if it's not already in).

My other initial reactions, for future iterations:
1. Using color alone might be problematic in terms of people being able to distinguish the states. 
2. It's probably not clear to a new user what's being indicated at all.

My first thought was some kind of tick and cross, but that doesn't make it any clearer what's being indicated. I'll re-start using celltests and think about it again!

**Comment by ceball** [comment]
This issue - and the points above - were fixed in 0.2.3 (colored indicator plus text).
