### ISSUE TITLE
Distinguish between lint and tests in the lab UI

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#184]
There's no distinction between the "CELLTESTS" box and the "CELLTESTS - RULES" box in terms of tests vs. lint. Confusing to new users.

**Comment by timkpaine** [comment]
hows this?

![Screen Shot 2020-08-20 at 13 56 14](https://user-images.githubusercontent.com/3105306/90807748-f5125500-e2ec-11ea-95db-ac942a153bc8.png)

**Comment by ceball** [comment]
Looks better! Thanks

**Comment by ceball** [comment]
Fixed in 0.2.3
