### ISSUE TITLE
JupyterLab 3.0+ Support

### ISSUE THREAD

**Issue by traviscancode604** [jpmorganchase/nbcelltests#252]
**Is your feature request related to a problem? Please describe.**
We are running JupyterLab 3.2.8 and cannot use `nbcelltests` because of an extension installation error related to `jupyterlab_celltests`.

Error message:
`The extension "jupyterlab_celltests" does not yet support the current version of JupyterLab.`

**Describe the solution you'd like**
Would like to be able to run `pip install nbcelltests` per the documentation and have the package work for JupyterLab 3.2.8.

**Describe alternatives you've considered**
Alternative of downgrading JupyterLab version is not feasible. 

**Additional context**
Related to https://github.com/jpmorganchase/nbcelltests/issues/215

```
Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/apputils
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/codeeditor
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/codemirror
>=5.2.8 <5.3.0          >=4.0.0 <5.0.0 @jupyterlab/coreutils
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/docmanager
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/filebrowser
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/launcher
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/mainmenu
>=3.2.8 <3.3.0          >=2.0.0 <3.0.0 @jupyterlab/notebook
```

**Comment by timkpaine** [comment]
We already support jupyterlab 3+, just might need to do a new release
