### ISSUE TITLE
readthedocs link 404s

### ISSUE THREAD

**Issue by nakami** [jpmorganchase/nbcelltests#258]
**Describe the bug**
The provided link to [nbcelltests.readthedocs.io](https://nbcelltests.readthedocs.io/) leads to a 404 page.

**To Reproduce**

1. Click on [nbcelltests.readthedocs.io](https://nbcelltests.readthedocs.io/) on the repository's *About* section

**Expected behavior**
A. Get some further documentation with the provided link.
B. The link not existing in the first place.

**Comment by nakami** [comment]
Related PRs:

- https://github.com/jpmorganchase/nbcelltests/pull/23 (2019, June)
- https://github.com/jpmorganchase/nbcelltests/pull/47 (2019, October)
- https://github.com/jpmorganchase/nbcelltests/pull/253 (2022, April)

**Comment by timkpaine** [comment]
yep that's correct
