### ISSUE TITLE
Proposal: split the 'jupyter lab' part from the notebook testing/linting part

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#48]
Running from the command line to check a notebook (e.g. `python -m jupyterlab_celltests.test nb.ipynb`) is useful, and has nothing to do with jupyter lab.

The notebook linting/testing part could be called something like 'nb_celltests' or 'notebook_celltests'. (I'm sure someone could think of a better name. Ideally without an underscore! Maybe just celltests? Although the lint checking isn't really 'cell' related - it's got to be the whole notebook.)

jupyterlab_celltests would then just depend on/use the notebook checking tool. 

No rush for this as it won't change the functionality - I guess the main impact would be on understanding/adoption by others.

**Comment by timkpaine** [comment]
I'll leave this for after our `Enterprise Jupyter` proposal goes through

**Comment by ceball** [comment]
Another thing occurred to me to clarify at some point. Some (most?) of jupyterlab_celltests applies to notebooks in general, and doesn't depend on any specific kernel. E.g. the notebook structure tests presumably work as well for julia as they do for python. However, some of jupyterlab_celltests is specific to python. E.g. the lint checking is currently python only - you couldn't lint ipython, julia, etc etc.

**Comment by ceball** [comment]
Also to consider at the same time: jupyterlab_celltests calls pytest, but for non-jupyterlab use (e.g. command line), it might make more sense to be a pytest plugin.

**Comment by ceball** [comment]
We have done this. The project is now called "nbcelltests", and there's a jupyterlab_celltests labextension - which I am fine with even though I wonder if maybe it should have been jupyterlab_nbcelltests ;) ).
