### ISSUE TITLE
Feature request: command line options and config system

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#49]
I think it would be useful to be able to specify structure rules (cells per notebook, lines per cell, etc) from the command line (or config).

E.g. I might want to specify that all notebooks in my project should have no more than 10 lines per cell. (I could also imagine different rules for different directories if the directories have different purposes, and so on.) 

If rules are present in individual notebooks, they could override the global ones. I.e. make it more like typical linters, where rules are usually set globally, but can be overridden at various levels.

Currently, global rules override local rules in notebooks. This way around could also be desirable in certain scenarios.

**Comment by ceball** [comment]
Just to clarify: this is already supported when using celltests programmatically, just not from the command line.

**Comment by timkpaine** [comment]
https://github.com/jpmorganchase/nbcelltests/pull/198
