### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/nbcelltests#63]

**Comment by ceball** [comment]
@timkpaine do you mean, "get jupyter celltests onto conda-forge" (from where it could be taken into the "defaults" channel too)? Or just have a recipe here in the celltests repository, to use for building "our own" conda packages (e.g. on travis, which we might then make available somewhere)?

(The first one makes more sense to me in general. But you could also consider having a 'timkpaine' conda channel where you make available conda packages you've built.)

**Comment by timkpaine** [comment]
the former

**Comment by ceball** [comment]
xref https://github.com/conda-forge/staged-recipes/pull/11425

**Comment by ceball** [comment]
https://anaconda.org/conda-forge/nbcelltests
