### ISSUE TITLE
Option to ignore empty code cells in lint checks

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#83]
Many notebook interfaces (lab, classic) often insert an empty code cell at the end of the notebook. celltests should probably at least have an option to ignore empty code cells in things like code cell counts.

Also, definition of empty code cell?
  * Nothing at all?
  * Only comments?
  * Either (by option)

(EDIT: added 'either')

**Comment by vidartf** [comment]
> Also, definition of empty code cell?

Empty ast?

**Comment by ceball** [comment]
I think not a technical thing, but which do we want. 

E.g. do you want to prevent people from having loads of cells full of commented out code, or is that ok? Can argue both ways, I think. 

Same thing for line counts I guess.

**Comment by vidartf** [comment]
Oh, I guess my answer was implied in the technical bits: The standard python AST parser does not include comments, so my answer is: All cells that only contain whitespace and/or comments should be considered empty.

**Comment by ceball** [comment]
Thanks for explaining. Your vote is noted :) 

Someone else might want to prevent 30 cells full of commented-out code in their team's notebooks. 

I am probably voting to have the option either way, but with the default behavior being what you suggest. But I haven't really thought about it yet. 

(I haven't really thought about it yet because I believe nbcelltests currently has a somewhat confusing overlap between linting python code, linting notebook "structure", and testing, which I'd love to clarify first...)
