### ISSUE TITLE
Tests include all previous cells+tests, but they also all execute in the same kernel

### ISSUE THREAD

**Issue by ceball** [jpmorganchase/nbcelltests#94]
Each test executes all the previous tests, by design (by including the code of all previous tests in the given test method). However, all tests currently _also_ execute in the same kernel (unless you explicitly distribute each test to its own process). With `N` tests, test `n` is therefore run `N+1-n` times in the same kernel (e.g. with 10 tests, the 1st test executes 10 times in the same kernel).

Let me know if this is deliberate, e.g. because starting a kernel per test method is too slow, or for some other reason. ~~(In #90 I have actually made it an option, but the default is to have "fresh kernel per test".)~~

**Comment by vidartf** [comment]
Maybe we could run some pytest code in each kernel so that we can reuse the kernel, but ensure that each run has a clean intial context (globals/locals)?

**Comment by vidartf** [comment]
Me and @ceball had a call today, and I think we were able to find a decent optimization to ensure that each cell gets executed in the correct context, but with minimal amount of kernel restarts or duplicate code executions. Will update as it progresses.
